version: "3.8"
services:

  redis-db:
    image: redis:4.0.11
    container_name: redis-db
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - /tmp/redis/data/:/data
    networks:
      - carpark-microservice

  

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - carpark-microservice

  carpark-db:
    image: kartoza/postgis:15-3.3
    volumes:
      - postgis-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=car_park_db,accounts_db,bookings_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      # Add extensions you need to be enabled by default in the DB. Default are the five specified below
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting,postgis_tiger_geocoder
      - RUN_AS_ROOT=true
    ports:
      - "5432:5432"
    restart: on-failure
    healthcheck:
      test: "PGPASSWORD=postgres pg_isready -h 127.0.0.1 -U postgres -d car_park_db"
    networks:
      - carpark-microservice

  configserver:
    image: carpark/configserver
    ports:
      - "8071:8071"
    networks:
      - carpark-microservice
    depends_on:
      - zipkin
    deploy:
      resources:
        limits:
          memory: 700MB
    environment:
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans

  eurekaserver:
    image: carpark/eurekaserver
    ports:
      - "8070:8070"
    networks:
      - carpark-microservice
    depends_on:
      - configserver
    deploy:
      resources:
        limits:
          memory: 700MB
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_APPLICATION_NAME: eurekaserver
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans

  gatewayserver:
    image: carpark/gatewayserver
    ports:
      - "8072:8072"
    networks:
      - carpark-microservice
    depends_on:
      - configserver
      - eurekaserver
      - bookings
      - carparks
      - accounts
      - carpark-db
    deploy:
      resources:
        limits:
          memory: 700MB
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 180s
    environment:
      SPRING_APPLICATION_NAME: gatewayserver
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans

  accounts:
#    image: carpark-microservice/accounts:latest
    image: carpark/accounts
    ports:
      - "8080:8080"
    networks:
      - carpark-microservice
    depends_on:
      - configserver
      - eurekaserver
      - carpark-db
    deploy:
      resources:
        limits:
          memory: 700MB
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_APPLICATION_NAME: accounts
      SPRING_DATASOURCE_URL: jdbc:postgresql://carpark-db:5432/accounts_db
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans

  bookings:
    image: carpark/bookings
    ports:
      - "10000:10000"
    networks:
      - carpark-microservice
    depends_on:
      - configserver
      - eurekaserver
      - carpark-db
    deploy:
      resources:
        limits:
          memory: 700MB
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_APPLICATION_NAME: bookings
      SPRING_DATASOURCE_URL: jdbc:postgresql://carpark-db:5432/bookings_db
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans

  carparks:
    image: carpark/carparks
    ports:
      - "4000:4000"
    networks:
      - carpark-microservice
    depends_on:
      - configserver
      - eurekaserver
      - carpark-db
    deploy:
      resources:
        limits:
          memory: 700MB
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_APPLICATION_NAME: carparks
      SPRING_DATASOURCE_URL: jdbc:postgresql://carpark-db:5432/car_park_db
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans

volumes:
  postgis-data:
networks:
  carpark-microservice: