apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookings-deployment
  labels:
    app: bookings
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookings
  template:
    metadata:
      labels:
        app: bookings
    spec:
      containers:
      - name: bookings
        image: vtnhanhcmus/bookings:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 10000
        env:
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              name: carpark-configmap
              key: BOOKINGS_APPLICATION_NAME
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: carpark-configmap
              key: BOOKINGS_DATASOURCE_URL
        - name: SPRING_PROFILES_ACTIVE
          valueFrom: 
            configMapKeyRef:
              name: carpark-configmap
              key: SPRING_PROFILES_ACTIVE
        - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
          valueFrom: 
            configMapKeyRef:
              name: carpark-configmap
              key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
        - name: SPRING_CONFIG_IMPORT
          valueFrom: 
            configMapKeyRef:
              name: carpark-configmap
              key: SPRING_CONFIG_IMPORT
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom: 
            configMapKeyRef:
              name: carpark-configmap
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
apiVersion: v1
kind: Service
metadata:
  name: bookings-service
spec:
  selector:
    app: bookings
  type: NodePort
  ports:
    - protocol: TCP
      port: 10000
      targetPort: 10000
