apiVersion: v1
kind: ConfigMap
metadata:
  name: carpark-configmap
data:
    MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin-service:9411/api/v2/spans
    SPRING_PROFILES_ACTIVE: prod
    SPRING_CONFIG_IMPORT: configserver:http://configserver-service:8071/
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver-service:8070/eureka/
    EUREKA_APPLICATION_NAME: eurekaserver
    ACCOUNTS_APPLICATION_NAME: accounts
    CARPARK_APPLICATION_NAME: carpark
    BOOKINGS_APPLICATION_NAME: bookings
    GATEWAY_APPLICATION_NAME: gatewayserver
