apiVersion: apps/v1
kind: Deployment
metadata:
  name: carpark-db-deployment
  labels:
    app: carpark-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carpark-db
  template:
    metadata:
      labels:
        app: carpark-db
    spec:
      containers:
      - name: carpark-db
        image: kartoza/postgis:15-3.3
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: carpark-configmap
              key: CARPARK_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: carpark-configmap
              key: CARPARK_USER
        - name: POSTGRES_PASS
          valueFrom:
            configMapKeyRef:
              name: carpark-configmap
              key: CARPARK_PASS
--- 
apiVersion: v1
kind: Service
metadata:
  name: carpark-db-service
spec:
  selector:
    app: carpark-db
  type: NodePort
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432