apiVersion: apps/v1
kind: Deployment
metadata:
  name: carpark-etl-deployment
  labels:
    app: carpark-etl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carpark-etl
  template:
    metadata:
      labels:
        app: carpark-etl
    spec:
      containers:
      - name: carpark-etl
        image: vtnhanhcmus/carpark-etl:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        env:
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              name: carpark-configmap
              key: CARPARKETL_APPLICATION_NAME
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: carpark-configmap
              key: CARPARKETL_DATASOURCE_URL
        - name: SPRING_PROFILES_ACTIVE
          valueFrom: 
            configMapKeyRef:
              name: carpark-configmap
              key: SPRING_PROFILES_ACTIVE
        - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
          valueFrom: 
            configMapKeyRef:
              name: carpark-configmap
              key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
        - name: SPRING_CONFIG_IMPORT
          valueFrom: 
            configMapKeyRef:
              name: carpark-configmap
              key: SPRING_CONFIG_IMPORT
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom: 
            configMapKeyRef:
              name: carpark-configmap
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
apiVersion: v1
kind: Service
metadata:
  name: carpark-etl-service
spec:
  selector:
    app: carpark-etl
  type: NodePort
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
